name: lbp-glcm-pca-svm
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - opencv
  - joblib
  - openpyxl
  - jupyter
  - notebook
  - ipykernel
  - pip
